-- Sample queries 
create schema apis

Create table apis.todos (
id int primary key generated by default as identity,
done boolean not null default false,
task text not null,
due timestamptz
)

insert into apis.todos (task) values ('wiw'), ('tada'), ('shess')

create role anon nologin

grant usage on schema apis to anon
grant select on apis.todos to anon

create role authenticator noinherit login password 'root'
grant anon to authenticator